### ISSUE TITLE
请问一下，这一块的代码不开源吗

### ISSUE THREAD

**Issue by qo0581122** [EricZhu-42/SteamTradingSite-ID-Mapper#1]

**Comment by EricZhu-42** [comment]
你好，我不太确定这边的代码是否有开源的需求？

饰品 ID 映射关系是基本固定不变的，无需实时更新，我会定期更新该仓库内的信息。

如果是希望学习，这部分代码的实际运行流程类似于 [update_meta.py](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/sync/scripts/update_meta.py)，似乎没有再维护一份的需要。
