### ISSUE TITLE
I want to updata for you

### ISSUE THREAD

**Issue by Zwt122544** [EricZhu-42/SteamTradingSite-ID-Mapper#2]
now the count for skin is up to 2.4w,but your data is just 2.2w,i guess the 2024 skin you dont updata

**Comment by EricZhu-42** [comment]
Hi，我们的数据源主要来自于 Steam Market 的 CSGO/DOTA2 可交易物品列表，以及各大交易平台上架的物品列表。一般而言，每隔 2 周左右，我会主动进行一次数据更新，具体请参考该 repo 的 [commit 历史](https://github.com/EricZhu-42/SteamTradingSite-ID-Mapper/commits/main/)。

如果发现存在数据缺失，或数据内容存在错误（包括但不限于：名称、平台 ID 等），欢迎发起 PR 或 Issue 反馈，谢谢！

---

Hi, our data primarily come from the list of tradable items on the Steam Market for CSGO/DOTA2, as well as the item listings on 3rd-party trading platforms. Usually, I update the data every 2 weeks. Please refer to the [commit history](https://github.com/EricZhu-42/SteamTradingSite-ID-Mapper/commits/main/) of this repository for these updates.

If you find any missing data or errors in the data (including but not limited to: names, platform IDs, etc.), please feel free to start a PR or Issue. Thank you!
