### ISSUE TITLE
10月新出的饰品好像都没更新呢

### ISSUE THREAD

**Issue by wangxingzhen** [EricZhu-42/SteamTradingSite-ID-Mapper#4]

**Comment by EricZhu-42** [comment]
Hi，感谢反馈！我一般两周更新一次数据，预计这两天会将最新的数据补上。

**Comment by EricZhu-42** [comment]
已在 [03c3f10 ](https://github.com/EricZhu-42/SteamTradingSite-ID-Mapper/commit/03c3f1098ee5632a2a7f0e2b96febf43c27d317e) 中更新了 508 个 CSGO 饰品及 23 个 Dota2 饰品。

如有信息不全的情况，欢迎随时反馈或直接发起 PR~
