### ISSUE TITLE
上海Major的数据希望能尽快更新

### ISSUE THREAD

**Issue by Latiao-lf** [EricZhu-42/SteamTradingSite-ID-Mapper#5]
感谢佬，希望能抽空更新一下~

**Comment by EricZhu-42** [comment]
好的，感谢反馈，我这两天会更新上~

**Comment by EricZhu-42** [comment]
bcf3bb1 更新了 C5 & IGXE & UUYP 的数据； 8ce38db 补充了 BUFF 数据。

如有缺失请反馈，谢谢！感谢 @wangxingzhen 的帮助！
