### ISSUE TITLE
上海major目前缺少的数据

### ISSUE THREAD

**Issue by wangxingzhen** [EricZhu-42/SteamTradingSite-ID-Mapper#7]
根据[https://csgoskins.gg](https://csgoskins.gg) 网站的信息，目前还缺少七个纪念包、冠军印花胶囊(还没出)

**Comment by wangxingzhen** [comment]
在这里我补充一下悠悠有品、buff、igxe的id，由于没有c5，所以暂时提供不了c5的id，以及steam的name_id不太清楚咋回事，期待大佬补全
`
[
    {
        "market_hash_name": "Shanghai 2024 Mirage Souvenir Package",
        "uuyp_id": "110594",
        "igxe_id": "687469",
        "buff_id": "1114852"
    },
    {
        "market_hash_name": "Shanghai 2024 Nuke Souvenir Package",
        "uuyp_id": "110596",
        "igxe_id": "687508",
        "buff_id": "1114855"
    },
    {
        "market_hash_name": "Shanghai 2024 Inferno Souvenir Package",
        "uuyp_id": "110597",
        "igxe_id": "687484",
        "buff_id": "1114857"
    },
    {
        "market_hash_name": "Shanghai 2024 Anubis Souvenir Package",
        "uuyp_id": "110593",
        "igxe_id": "687467",
        "buff_id": "1114851"
    },
    {
        "market_hash_name": "Shanghai 2024 Vertigo Souvenir Package",
        "uuyp_id": "110591",
        "igxe_id": "687468",
        "buff_id": "1114846"
    },
    {
        "market_hash_name": "Shanghai 2024 Ancient Souvenir Package",
        "uuyp_id": "110592",
        "igxe_id": "687472",
        "buff_id": "1114845"
    },
    {
        "market_hash_name": "Shanghai 2024 Dust II Souvenir Package",
        "uuyp_id": "110595",
        "igxe_id": "687470",
        "buff_id": "1114854"
    }
]
`

**Comment by EricZhu-42** [comment]
感谢反馈！抱歉前几天有点忙，一直没来得及处理。我会尽快把这部分数据合并进来。

**Comment by EricZhu-42** [comment]
已于 2e0b78e 与 97c37c2 中更新完成，感谢反馈！
